
## Pandas Demo Examples
Demo examples based on and selected from material by UZH ZI & David Pinezich.

* Pandas is a newer package built on top of NumPy
* NumPy is very useful for numerical computing tasks* 
* Pandas allows more flexibility: Attaching labels to data, working with missing data, etc.

In [56]:
import pandas as pd
pd.__version__

'2.2.1'

In [57]:
import numpy as np # We will need NumPy throughout this course day
np.__version__

'1.26.2'

## The Pandas Objects
* Pandas objects are enhanced versions of NumPy arrays: The rows and columns are identified with labels rather than simple integer indices
* `Series` object: A one-dimensional array of indexed data
* `DataFrame` object: A two-dimensional array with both flexible row indices and flexible column names

## The Pandas `Series` Object
* A Pandas `Series` object is a one-dimensional array of indexed data
 * NumPy array: has an _implicitly_ defined integer index
 * A `Series` object uses by default integer indices:

In [3]:
data1 = pd.Series([100,200,300])
data1

0    100
1    200
2    300
dtype: int64

* A `Series` object can have an _explicitly_ defined index associated with the values:

In [4]:
data2 = pd.Series([100,200,300], index=["a","b","c"])
data2

a    100
b    200
c    300
dtype: int64

* We can access the index labels by using the `index` attribute:

In [5]:
d2ind = data2.index
d2ind

Index(['a', 'b', 'c'], dtype='object')

* A Python dictionary maps arbitrary keys to a set of arbitrary values
* A `Series` object maps _typed_ keys to a set of _typed_ values
 * "Typed" means we know the type of the indices and elements beforehand, making Pandas Series objects much more efficient than Python dictionaries for certain operations
* We can construct a `Series` object directly from a Python dictionary:

In [6]:
data_dict = pd.Series({"c":123,"a":30,"b":100})
data_dict

c    123
a     30
b    100
dtype: int64

* _Note_: The index for the `Series` is drawn from the sorted keys

## The Pandas `DataFrame` Object
* A `DataFrame` object is an analog of a two-dimensional array both with flexible row indices and flexible column names
 * Both the rows and columns have a generalized index for accessing the data
 * The row indices can be accessed by using the `index` attribute
 * The column indices can be accessed by using the `columns` attribute
 
## Constructing `DataFrame` Objects
* You can think of a `DataFrame` as a sequence of aligned `Series` objects, meaning that each column of a `DataFrame` is a `Series`

In [7]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135,
                    'Alabama': 232323232}
population = pd.Series(population_dict)

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)

In [8]:
population

California     38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Alabama       232323232
dtype: int64

In [9]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [10]:
states = pd.DataFrame({'population': population,'area': area})
states

            population      area
Alabama      232323232       NaN
California    38332521  423967.0
Florida       19552860  170312.0
Illinois      12882135  149995.0
New York      19651127  141297.0
Texas         26448193  695662.0

In [12]:
states.index

Index(['Alabama', 'California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [11]:
states.columns

Index(['population', 'area'], dtype='object')

Renaming columns can be done using the same `columns` attribute:

In [ ]:
states.columns = ["population", "area / km2"]

* There are multiple ways to construct a `DataFrame` object
 * From a single `Series` object

In [13]:
pd.DataFrame(population, columns=["population"])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Alabama      232323232

 * From a list of dictionaries:

In [17]:
x = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4, 'd':100}, {'a':1000, 'c':22, 'g': 123}])
print(x)
value = 3

        a    b     c      d      g
0     1.0  2.0   NaN    NaN    NaN
1     NaN  3.0   4.0  100.0    NaN
2  1000.0  NaN  22.0    NaN  123.0

 * From a dictionary of `Series` objects:

In [18]:
pd.DataFrame({'population': population, 'area': area})

            population      area
Alabama      232323232       NaN
California    38332521  423967.0
Florida       19552860  170312.0
Illinois      12882135  149995.0
New York      19651127  141297.0
Texas         26448193  695662.0

 * From a two-dimensional NumPy array:

In [19]:
rng = np.random.RandomState(0) # Ensure that the same random numbers are generated each time we run this code
pd.DataFrame(rng.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.548814  0.715189
b  0.602763  0.544883
c  0.423655  0.645894

## Data Selection in `Series`

`Series` as a dictionary: 
 * Select elements by key, e.g. `data['a']`
 * Modify the `Series` object with familiar syntax, e.g. `data['e'] = 100`
 * Check if a key exists by using the `in` operator
 * Access all the keys by using the `keys()` method
 * Access all the values by using the `items()` method

In [20]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [21]:
data['b']

0.5

In [22]:
'a' in data

True

In [23]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [24]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [29]:
data['e'] = 1.25
data['a'] = 123
data

a     123
b     0.5
c    0.75
d     1.0
e    1.25
dtype: object

* `Series` as one-dimensional array: 
 * Select elements by the implicit integer index, e.g. `data[0]`
 * Select elements by the explicit index, e.g. `data['a']`
 * Select slices (by using an implicit integer index or an explicit index)
   * _Important_: Slicing with an explicit index (e.g., `data['a':'c']`) will _include_ the final index in the slice, while slicing with an implicit index (e.g., `data[0:3]`) will _exclude_ the final index from the slice
 * Use masking operations, e.g., `data[data < 3]`

In [30]:
data['a':'c'] # Slicing by explicit index

a     123
b     0.5
c    0.75
dtype: object

In [31]:
data[0:2] # Slicing by implicit index

a    123
b    0.5
dtype: object

In [25]:
data[(data > 0.3) & (data < 0.8)] # Masking operation

b    0.50
c    0.75
dtype: float64

## Data Selection in `DataFrame`
* `DataFrame` as a dictionary of related `Series` objects: 
 * Select `Series` by the column name, e.g. `df['area']`
 * Modify the `DataFrame` object with familiar syntax, e.g. `df['c3'] = df['c2']/ df['c1']`

In [32]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127, 'Florida': 19552860,
                        'Illinois': 12882135})

data = pd.DataFrame({'area': area, 'population': population})
data

              area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [33]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [35]:
data['density'] = data['population'] / data['area']
data

              area  population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

* `DataFrame` as two-dimensional array: 
 * Access the underlying NumPy data array by using the `values` attribute
   * `df.values[0]` will select the first row
 * Use the `iloc` indexer to index, slice, and modify the data by using the implicit integer index
 * Use the `loc` indexer to index, slice, and modify the data by using the explicit index

In [39]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [40]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [38]:
data.iloc[:3, :2] # Use implicit indices

              area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [37]:
data.loc[:'Illinois', :'population'] # Use explicit indices

              area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [41]:
data.iloc[0, 2] = 90
data

              area  population     density
California  423967    38332521   90.000000
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

## Ufuncs and Pandas
* Pandas is designed to work with Numpy, thus any NumPy ufunc will work on Pandas Series and `DataFrame` objects
* _Index preservation_: Indices are preserved when a new Pandas object will come out after applying ufuncs
* _Index alignment_: Pandas will align indices in the process of performing an operation
 * Missing data is marked with `NaN` ("Not a Number")
 * We can specify on how to fill value for any elements that might be missing by using the optional keyword fill_value: `A.add(B, fill_value=0)`
 * We can also use the `dropna()` method to drop missing values
* _Note_: Any of the ufuncs discussed for NumPy can be used in a similar manner with Pandas objects

### Ufuncs: Index Preservation

In [42]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [43]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [44]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [45]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

### Ufuncs: Index Alignment

In [46]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [47]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [48]:
(population / area).dropna()

California    90.413926
Texas         38.018740
dtype: float64

In [ ]:
df1 = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
df1

   A   B
0  1  11
1  5   1

In [ ]:
df2 = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
df2

   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [ ]:
df2 + df1

      A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)

      A     B    C
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0

## Ufuncs: Operations Between DataFrame and Series
* Operations between a `DataFrame` and a `Series` are similar to operations between a two-dimensional and one-dimensional NumPy array (e.g., compute the difference of a two-dimensional array and one of its rows)

In [53]:
rng = np.random.RandomState(2)
A = rng.randint(10, size=(3, 4))
A

array([[8, 8, 6, 2],
       [8, 7, 2, 1],
       [5, 4, 4, 5]])

In [54]:
A - A[0] # Subtract the first row of A from A itself

array([[ 0,  0,  0,  0],
       [ 0, -1, -4, -1],
       [-3, -4, -2,  3]])

In [55]:
B = rng.randint(10, size=(3, 4))
B

array([[7, 3, 6, 4],
       [3, 7, 6, 1],
       [3, 5, 8, 4]])

In [56]:
df = pd.DataFrame(B, columns=list('QRST'))
df

   Q  R  S  T
0  7  3  6  4
1  3  7  6  1
2  3  5  8  4

In [57]:
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1 -4  4  0 -3
2 -4  2  2  0

In [61]:
df.subtract(df['R'], axis=0) # We can also subtract column-wise

   Q  R  S  T
0  4  0  3  1
1 -4  0 -1 -6
2 -2  0  3 -1

## Reading and Writing Data with Pandas
### File Types
* We will work with _plaintext files_ only in this session; these contain only basic text characters and do not include font, size, or color information
 * _Binary files_ are all other file types, such as PDFs, images, executable programs etc.
 
### The Current Working Directory
* Every program that runs on your computer has a _current working directory_
 * It's the directory from where the program is executed / run
 * _Folder_ is the more modern name for a directory
* The _root_ directory is the top-most directory and is addressed by `/` 
 * A directory `mydir1` in the root directory can be addressed by `/mydir1`
 * A directory `mydir2` within the `mydir1` directory can be address by `/mydir/mydir2`, and so on
 
### Absolute and Relative Paths
* An _absolute path_ begins always with the root folder, e.g. `/my/path/...`
* A _relative path_ is always relative to the program's current working directory
 * If a program's current working directory is `/myprogram` and the directory contains a folder files with a file `test.txt`, then the relative path to that file is just `files/test.txt` 
 * The absolute path to `test.txt` would be `/myprogram/files/test.txt` (note the root folder `/`)

In [6]:
pwd

'D:\\Google Drive\\Documents\\Python\\Python course\\APPD\\appd-dp-fs24\\2_material'

In [5]:
!ls # List folder content / for windows use !dir
!pwd # current working directory

Der Befehl "ls" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

### Reading Data with Pandas
* Pandas provides the `pandas.read_csv()` function to load data from a CSV file (or a file that uses a different delimiter than a comma)
 * The path you specify doesn't have to be on your hard disk; you can also provide the URL to a CSV file to read it directly into a Pandas object
 * We can set the optional argument `error_bad_lines` to `False` so that bad lines in the file get omitted and do not cause an error
 * Checkout the documentation to learn more about the optional arguments:<br>https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html
 
**Planets Data**: The _Planets_ dataset (available from the Seaborn package or the [`seaborn-data` repository](https://github.com/mwaskom/seaborn-data)) gives information on planets that astronomers have discovered around other stars (known as extrasolar planets or exoplanets for short). The file contains details on the 1000+ exoplanets discovered up to 2014.

In [7]:
planets = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/planets.csv")

In [8]:
planets.shape

(1035, 6)

In [9]:
planets.head(20)

             method  number  orbital_period    mass  distance  year
0   Radial Velocity       1      269.300000   7.100     77.40  2006
1   Radial Velocity       1      874.774000   2.210     56.95  2008
2   Radial Velocity       1      763.000000   2.600     19.84  2011
3   Radial Velocity       1      326.030000  19.400    110.62  2007
4   Radial Velocity       1      516.220000  10.500    119.47  2009
5   Radial Velocity       1      185.840000   4.800     76.39  2008
6   Radial Velocity       1     1773.400000   4.640     18.15  2002
7   Radial Velocity       1      798.500000     NaN     21.41  1996
8   Radial Velocity       1      993.300000  10.300     73.10  2008
9   Radial Velocity       2      452.800000   1.990     74.79  2010
10  Radial Velocity       2      883.000000   0.860     74.79  2010
11  Radial Velocity       1      335.100000   9.880     39.43  2009
12  Radial Velocity       1      479.100000   3.880     97.28  2008
13  Radial Velocity       3     1078.000000   2.530     14.08  1996
14  Radial Velocity       3     2391.000000   0.540     14.08  2001
15  Radial Velocity       3    14002.000000   1.640     14.08  2009
16  Radial Velocity       1        4.230785   0.472     15.36  1995
17  Radial Velocity       5       14.651000   0.800     12.53  1996
18  Radial Velocity       5       44.380000   0.165     12.53  2004
19  Radial Velocity       5     4909.000000   3.530     12.53  2002

In [10]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [11]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

### Some Interesting Data Sources
* Federal Statistical Office: https://www.bfs.admin.ch/bfs/en/home/statistics/catalogues-databases/data.html 
* OpenData: https://opendata.swiss/en/ 
* United Nations: http://data.un.org/ 
* World Health Organization: http://apps.who.int/gho/data/node.home 
* World Bank: https://data.worldbank.org/ 
* Kaggle: https://www.kaggle.com/datasets 
* Cern: http://opendata.cern.ch/
* Nasa: https://data.nasa.gov/ 
* FiveThirtyEight: https://github.com/fivethirtyeight/data

## Aggregating and Grouping Data in Pandas

### Simple Aggregation in Pandas
* As with one-dimensional NumPy array, for a Pandas `Series` the aggregates return a single value
* For a `DataFrame`, the aggregates return by default results within each column
* Pandas `Series` and `DataFrames` include all of the common NumPy aggregates
 * In addition, there is a convenience method `describe()` that computes several common aggregates for each column and returns the result

In [12]:
rng = np.random.RandomState(3)
ser = pd.Series(rng.rand(5))
ser

0    0.550798
1    0.708148
2    0.290905
3    0.510828
4    0.892947
dtype: float64

In [13]:
ser.sum()

2.9536250236509423

In [14]:
ser.mean()

0.5907250047301884

In [15]:
df = pd.DataFrame({'A': rng.rand(5), 'B': rng.rand(5)})
df

          A         B
0  0.896293  0.029876
1  0.125585  0.456833
2  0.207243  0.649144
3  0.051467  0.278487
4  0.440810  0.676255

In [18]:
df.mean()

A    0.344280
B    0.418119
dtype: float64

In [19]:
df.mean(axis='columns')

0    0.463085
1    0.291209
2    0.428193
3    0.164977
4    0.558532
dtype: float64

In [25]:
df.describe()

              A         B
count  5.000000  5.000000
mean   0.344280  0.418119
std    0.341461  0.270062
min    0.051467  0.029876
25%    0.125585  0.278487
50%    0.207243  0.456833
75%    0.440810  0.649144
max    0.896293  0.676255

### Split, Apply, Combine
* _Split_: Break up and group a DataFrame depending on the value of the specified key
* _Apply_: Apply some function, usually an aggregate, transformation, or filtering, within the individual groups
* _Combine_: Merge the results of these operations into an output array

### The `GroupBy` Object
* The `groupBy()` method returns a `DataFrameGroupBy`: It's a special view of the `DataFrame`
 * Helps get information about the groups, but does no actual computation until the aggregation is applied ("lazy evaluation", i.e. evaluate only when needed)
 * Apply an aggregate to this `DataFrameGroupBy` object: This will perform the appropriate apply/combine steps to produce the desired result
   * You can apply any Pandas or NumPy aggregation function
 * Other important operations made available by a `GroupBy` are _filter_, _transform_, and _apply_

In [38]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(1,7)})
df

  key  data
0   A     1
1   B     2
2   C     3
3   A     4
4   B     5
5   C     6

In [39]:
groupby_key = df.groupby('key')
groupby_key.groups

{'A': [0, 3], 'B': [1, 4], 'C': [2, 5]}

In [42]:
df.groupby('key').sum()

     data
key
A       5
B       7
C       9

### Column Indexing and Iterating Over Groups
* The `GroupBy` object supports column indexing in the same way as the `DataFrame`, and returns a modified `GroupBy` object
* The `GroupBy` object also supports direct iteration over the groups, returning each group as a Series or `DataFrame`

In [43]:
planets.groupby('method')

In [44]:
planets.groupby('method')['orbital_period']

In [45]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [46]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)