In [1]:
import pandas as pd 
import numpy as np

In [2]:
inventory= pd.read_csv("inventory_solids.csv")
inventory

             Name  sum formula   amount(g)
0  sodium sulfate       Na2SO4         980
1  copper acetate       CuOAc2         100
2         quinine   C20H24N2O2          45
3  copper acetate       CuOAc2          32
4  copper bromide         CuBr          56
5  copper acetate       CuOAc2         250

In [3]:
inventory.columns=['name','sum_formula','amount(g)']
inventory.columns

Index(['name', 'sum_formula', 'amount(g)'], dtype='str')

In [ ]:
inventory.values[1]  # returns all the values in that given row

array(['copper acetate', ' CuOAc2', 100], dtype=object)

In [9]:
inventory['amount (kg)'] = inventory['amount(g)']/1000
inventory

             name  sum_formula  amount(g)  amount (kg)
0  sodium sulfate       Na2SO4        980        0.980
1  copper acetate       CuOAc2        100        0.100
2         quinine   C20H24N2O2         45        0.045
3  copper acetate       CuOAc2         32        0.032
4  copper bromide         CuBr         56        0.056
5  copper acetate       CuOAc2        250        0.250

In [7]:
inventory.drop(['amount (kg)'], axis=1, inplace=True)

In [8]:
inventory

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1  copper acetate       CuOAc2        100
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32
4  copper bromide         CuBr         56
5  copper acetate       CuOAc2        250

In [10]:
inventory=inventory.drop(['amount (kg)'], axis =1)

In [11]:
inventory

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1  copper acetate       CuOAc2        100
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32
4  copper bromide         CuBr         56
5  copper acetate       CuOAc2        250

In [12]:
inventory.loc[len(inventory)]=['Sodium Chloride','NaCl',100]

inventory

              name  sum_formula  amount(g)
0   sodium sulfate       Na2SO4        980
1   copper acetate       CuOAc2        100
2          quinine   C20H24N2O2         45
3   copper acetate       CuOAc2         32
4   copper bromide         CuBr         56
5   copper acetate       CuOAc2        250
6  Sodium Chloride         NaCl        100

In [13]:
inventory.drop([5,6],inplace=True)
inventory

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1  copper acetate       CuOAc2        100
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32
4  copper bromide         CuBr         56

In [18]:
inventory2= pd.read_csv("inventory_solids.csv")
inventory2.columns=['name','sum_formula','amount(g)']

In [19]:
inventory3= pd.concat([inventory, inventory2], axis=0, ignore_index=True)
inventory3

              name  sum_formula  amount(g)
0   sodium sulfate       Na2SO4        980
1   copper acetate       CuOAc2        100
2          quinine   C20H24N2O2         45
3   copper acetate       CuOAc2         32
4   copper bromide         CuBr         56
5   sodium sulfate       Na2SO4        980
6   copper acetate       CuOAc2        100
7          quinine   C20H24N2O2         45
8   copper acetate       CuOAc2         32
9   copper bromide         CuBr         56
10  copper acetate       CuOAc2        250

In [20]:
inventory3.to_csv("complete_inventory.csv",index=False)

In [23]:
inventory_grouped=inventory3.groupby(['name'])[['amount(g)']].sum()
inventory_grouped

                amount(g)
name
copper acetate        514
copper bromide        112
quinine                90
sodium sulfate       1960

In [25]:
amount_mean_formula=inventory3.groupby(['sum_formula'])[['amount(g)']].mean()
amount_mean_formula

             amount(g)
sum_formula
C20H24N2O2        45.0
CuBr              56.0
CuOAc2           102.8
Na2SO4           980.0

In [ ]:
# apply

inventory3["new_amount"]= inventory3["amount(g)"].apply(lambda x: x+111)


#lambda x: x+111  this is just a placeholder for any function, we can do the operations like sortig, ordering,filtering, etc
inventory3

              name  sum_formula  amount(g)  new_amount
0   sodium sulfate       Na2SO4        980        1091
1   copper acetate       CuOAc2        100         211
2          quinine   C20H24N2O2         45         156
3   copper acetate       CuOAc2         32         143
4   copper bromide         CuBr         56         167
5   sodium sulfate       Na2SO4        980        1091
6   copper acetate       CuOAc2        100         211
7          quinine   C20H24N2O2         45         156
8   copper acetate       CuOAc2         32         143
9   copper bromide         CuBr         56         167
10  copper acetate       CuOAc2        250         361